app_id = "saga-orchestrator"
app_env = "dev"

kafka_brokers = ["localhost:9092"]
kafka_group_orchestrator = "saga-orchestrator-orc"

http_addr = ":8082"

postgres_url = "postgres://postgres:postgres@localhost:5432/saga?sslmode=disable"

categorize_enabled = false
