name: Build & Push (GHCR)
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  packages: write
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/quiby-ai/saga-orchestrator:${{ github.sha }}
            ghcr.io/quiby-ai/saga-orchestrator:main
          # optional: multiarch
          # platforms: linux/amd64,linux/arm64
